AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - !ruby/regexp /(vendor|bundle|bin|db|tmp)\/.*/
  DisplayCopNames: true
  DisplayStyleGuide: true
  # https://github.com/bbatsov/rubocop/blob/master/manual/caching.md
  # https://github.com/bbatsov/rubocop/blob/e8680418b351491e111a18cf5b453fc07a3c5239/config/default.yml#L60-L77
  UseCache: true
  CacheRootDirectory: tmp

Rails:
  Enabled: true

Style/Alias:
  EnforcedStyle: prefer_alias

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/AbcSize:
  Max: 15

Metrics/ClassLength:
  Max: 100
  Exclude:
    - test/**/*.rb

Metrics/CyclomaticComplexity:
  Max: 6

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 7

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/MissingElse:
  Enabled: true
  EnforcedStyle: case

Style/EmptyElse:
  EnforcedStyle: empty

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: line_count_based

Style/SignalException:
  EnforcedStyle: semantic

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: no_comma

Style/DotPosition:
  EnforcedStyle: leading
