language: ruby

sudo: false

rvm:
  - 2.1
  - 2.2.6
  - 2.3.3

install: bundle install --path=vendor/bundle --retry=3 --jobs=3
cache:
  directories:
    - vendor/bundle

script:
  - bundle exec rake ci
after_success:
  - codeclimate-test-reporter
env:
  matrix:
    - "RAILS_VERSION=4.1"
    - "RAILS_VERSION=4.2"
    - "RAILS_VERSION=5.0"
    - "RAILS_VERSION=master"

matrix:
  exclude:
  - rvm: 2.1
    env: RAILS_VERSION=master
  - rvm: 2.1
    env: RAILS_VERSION=5.0
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
