language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - ruby-head
  - jruby-19mode
  - ruby-head

sudo: false

install: bundle install --path=vendor/bundle --retry=3 --jobs=3
cache:
  directories:
    - vendor/bundle

env:
  - "RAILS_VERSION=4.0"
  - "RAILS_VERSION=4.1"
  - "RAILS_VERSION=4.2"
  - "RAILS_VERSION=master"

matrix:
  allow_failures:
    - rvm: ruby-head
    - env: "RAILS_VERSION=master"
