version: '{build}'

skip_tags: true

environment:
  matrix:
    - ruby_version: "193"
    - ruby_version: "193-x64"
    - ruby_version: "200"
    - ruby_version: "200-x64"
    - ruby_version: "21"
    - ruby_version: "21-x64"
    - ruby_version: "22"
    - ruby_version: "22-x64"

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem install bundler
  - bundle install --retry=3

test_script:
  - RAILS_ENV=test bundle exec rake

build: off
